name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Lombok
        run: mvn org.projectlombok:lombok-maven-plugin:1.18.22:delombok

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Tests
        run: mvn test
